project:
  type: website
  output-dir: _site

website:
  title: "Stablecoins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: yield_bearing.html
        text: YBS

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true 