name: 'curve'
version: '1.0'
config-version: 2

model-paths: ["models"]
profile: 'etherscan_raw'

models:
  curve:
    +materialized: table
    # +schema: st1

# Configure source database attachment
vars:
  source_database_path: "../../data/raw/raw_curve.duckdb"
